### ISSUE TITLE
Problems about the performance

### ISSUE THREAD

**Issue by Mrkkew** [cvlab-yonsei/LbA#1]
I have run your source code on both SYSU and RegDB datasets, but I didn't get the performance of your paper. 
So I want to know how to set the hyper-parameter to get the performance of your paper?

**Comment by sanghoooon** [comment]
Hi. Thank you for your interest in our work.

I highly recommend using the provided docker image. This will set your environment identical to ours, helping you to obtain proper performances. If you still run into issues even with the docker image, please let us know by replying. All the results reported in our paper is obtained by taking an average value over 4 identical executions, so we are pretty confident that the results are reproducible.

In our work, the only major hyper-parameter to be tuned is \lambda_{DT} (lw_dt in train.py), which is set to 0.5 by default.
