### ISSUE TITLE
something about run this code

### ISSUE THREAD

**Issue by zhuchuanleiqq** [cvlab-yonsei/LbA#4]
thanks for your code, there is something wrong when i run you  code,in this line:
loss = torch.mean(comask_pos * self.criterion(feat, feat_recon_pos, feat_recon_neg))
the wrong is:RuntimeError: The size of tensor a (9) must match the size of tensor b (18) at non-singleton dimension 3
could you  give me some help?

**Comment by sanghoooon** [comment]
Could you provide shapes of feat, feat_recon_pos, feat_recon_neg ?

**Comment by zhuchuanleiqq** [comment]
this three is all [64, 1024, 18, 9],i also print the shape of self.criterion(feat, feat_recon_pos, feat_recon_neg),it is [64, 1024, 18],the last dimension is disappear,i think the reason is the setting of the nn.TripletMarginLoss(margin=0.3, p=2.0, reduce=False),also,i print the shape of comask_pos,it is [64, 1, 18, 9]

**Comment by sanghoooon** [comment]
Could you specify your pytorch version?

**Comment by zhuchuanleiqq** [comment]
python 3.7

**Comment by sanghoooon** [comment]
**PyTorch** version?

**Comment by zhuchuanleiqq** [comment]
pytorch 1.10.1

**Comment by sanghoooon** [comment]
Please check out the README.md file: our implementation is based on PyTorch 1.7.1
The behaviour within nn.TripletMarginLoss may differ across PyTorch versions. 
You might want to reshape tensors prior to passing them through nn.TripletMarginLoss.

**Comment by zhuchuanleiqq** [comment]
ok ,thank you for your help,may i ask what is the shape of your implementation about the self.criterion(feat, feat_recon_pos, feat_recon_neg)?

**Comment by sanghoooon** [comment]
All of them have to be [batch size, fdim, H, W].
Check out `soft_warping` in model.py

**Comment by cq0907** [comment]
> All of them have to be [batch size, fdim, H, W]. Check out `soft_warping` in model.py

I have the same problem, so may i want to ask what is the shape of your implementation about the comask_pos?

**Comment by sanghoooon** [comment]
Below are i/o dimensions for ```compute_comask``` that outputs ```comask_pos```:
* ```matching_pr``` [bs, hw, hw]
* ```mask_q``` [bs, 1, h, w]
* ```mask_k``` [bs, 1, h, w]
* ```comask``` [bs, 1, h, w]

where h and w are height and width of feature maps, respectively.

**Comment by cq0907** [comment]
> Below are i/o dimensions for `compute_comask` that outputs `comask_pos`:
> 
> * `matching_pr` [bs, hw, hw]
> * `mask_q` [bs, 1, h, w]
> * `mask_k` [bs, 1, h, w]
> * `comask` [bs, 1, h, w]
> 
> where h and w are height and width of feature maps, respectively.

OK, thank you!
