### ISSUE TITLE
How to visualize the heat map？

### ISSUE THREAD

**Issue by cq0907** [cvlab-yonsei/LbA#6]
Excuse me! I am interested interested in generating the heat map in this paper, there exists the code in this repository?

![image](https://user-images.githubusercontent.com/39946114/204090433-64a4144b-e16a-4947-8c57-ef4b147e6169.png)

**Comment by sanghoooon** [comment]
Hello, thank you for your interest in our work. 

Although we don't have a plan to release the visualization codes, 
I think you can refer to [this thread](https://stackoverflow.com/questions/46020894/superimpose-heatmap-on-a-base-image-opencv-python) for overlaying heatmaps and images using `cv2` library. 
We upscaled mask using bilinear interpolation to match height/width dimensions for an input image. 

Good luck!
